version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"

  inventory-service:
    container_name: inventory-service
    image: inventory-service
    ports:
      - "8080:8080"
    restart: "always"
